#! /usr/bin/env sh

printUsage() {
	echo  "\nUsage:\n"
	echo  "  riakcli list buckets                       -> Lists all the buckets available in RIAK"
	echo  "  riakcli list keys [bucket-name]            -> Lists all keys in a given bucket"
	echo  "  riakcli list object [bucket-name] [key]    -> Lists the object associated with a given key in a specified bucket"
	echo  ""
	echo  "  riakcli delete bucket [bucket-name]        -> Deletes all objects in a specified bucket"
	echo  "  riakcli delete object [bucket-name] [key]  -> Deletes an object in a given bucket"
	echo  "  riakcli flush                              -> Deletes all the buckets in RIAK"
	echo  ""
	echo  "  riakcli ping                               -> Connects to RIAK instance for status"
	echo  "  riakcli help                               -> Displays this usage information"	
}

printInvalidUsage() {
	echo "\n********************************************************"
	echo "ERROR: Invalid Usage (wrong/missing command arguments)"
	echo "********************************************************"

	printUsage
}

listAllBuckets() {
	curl ${RIAK_BASE_URL}/buckets?buckets=true
}

listKeysInBucket() {
	curl ${RIAK_BASE_URL}/buckets/$1/keys?keys=true
}

listObject() {
	local BUCKET=$1
	local KEY=$2

	curl ${RIAK_BASE_URL}/riak/${BUCKET}/${KEY}
}

deleteBucket() {
	local BUCKET=$1
	
	for KEY in `listKeysInBucket ${BUCKET} | sed -e 's/^.*\[//g' -e 's/"//g' -e 's/\]\}//g' -e 's/,/\'$'\n/g'`;
    do
        deleteObject ${BUCKET} ${KEY}
    done;
}

deleteObject() {
	local BUCKET=$1
	local KEY=$2

	curl -XDELETE ${RIAK_BASE_URL}/riak/${BUCKET}/${KEY};
}

flush() {
	for BUCKET in  `listAllBuckets | cut -d ':' -f2 | sed -e 's/^.*\[//g' -e 's/"//g' -e 's/\]\}//g' -e 's/,/\'$'\n/g'`;
	do
		echo "Deleting bucket - ${BUCKET}"
		deleteBucket ${BUCKET}
	done;
}

list() {
	case "$1" in
		"buckets" )			
			listAllBuckets
			;;
		"keys" )
			if [ -z "$2" ]; then
				printInvalidUsage
				exit	
			fi
			listKeysInBucket $2
			;;
		"object" )
			if [[ -z "$2" ||  -z "$3" ]]; then
				printInvalidUsage
				exit	
			fi
			listObject $2 $3			
			;;
		* )
			printInvalidUsage			
			;;
	esac	
}

delete() {
	case "$1" in
		"bucket" )
			if [ -z "$2" ]; then
				printInvalidUsage
				exit	
			fi
			deleteBucket $2
			;;
		"object" )
			if [[ -z "$2" ||  -z "$3" ]]; then
				printInvalidUsage
				exit	
			fi
			deleteObject $2 $3		
			;;
		* )
			printInvalidUsage			
			;;			
	esac
}

ping() {
	curl ${RIAK_BASE_URL}/ping
}

__init__() {

	RIAK_HOST="localhost"
	RIAK_PORT=8098

	if [ -f "$HOME/.riakclirc" ]; then . "$HOME/.riakclirc"; fi

	export RIAK_PORT RIAK_PORT
	RIAK_BASE_URL="http://${RIAK_HOST}:${RIAK_PORT}"
	export RIAK_BASE_URL



	case "$1" in
		"help" )
			printUsage
			;;
		"ping" )
			ping
			;;
		"list" )
			shift
			list $*
			;;
		"delete" )
			shift
			delete $*
			;;
		"flush" )
			flush
			;;
		* )
			printUsage
			;;
	esac	
}

__init__ $*